In [4]:
import numpy as np
matrix = np.random.randint(0, 101, size=(6, 4))
print(matrix)

[[ 78  40  41  11]
 [ 89  88   0  21]
 [ 68 100  90  70]
 [ 70  46  41  46]
 [ 72  33  55  23]
 [  2  30  11  55]]


In [5]:
matrix[4:5] = matrix[0] + matrix[2]

In [6]:
print(matrix[4:5])

[[146 140 131  81]]


In [7]:
print(matrix)

[[ 78  40  41  11]
 [ 89  88   0  21]
 [ 68 100  90  70]
 [ 70  46  41  46]
 [146 140 131  81]
 [  2  30  11  55]]


In [8]:
matrix[5:6]= matrix[1] + matrix[3]

In [9]:
print(matrix[5:6])

[[159 134  41  67]]


In [17]:
print(matrix)

[[ 78  40  41  11]
 [ 89  88   0  21]
 [ 68 100  90  70]
 [ 70  46  41  46]
 [146 140 131  81]
 [159 134  41  67]]
